set -s escape-time 0
set -g mouse on
setw -g mode-keys vi
# vi style v
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
# vi style ctrl+v
bind-key -Tcopy-mode-vi 'C-v' send -X begin-selection \; send -X rectangle-toggle
# 200MB max memory for scroll back buffer
set-option -g history-limit 20000000
set -g base-index 1
setw -g pane-base-index 1

# Number of characters for session name to show in the left of the status bar
set -g status-left-length 20

# Fix window rename by ranger
# set-option -g allow-rename off

set-option -g allow-rename on
set-option -g automatic-rename on

# Enable focus events (in tmux if claude changes files)
set -g focus-events on

# map prefix to 'C-a'
# but keep 'C-b' as a prefix key too
set-option -g prefix2 C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind-key C-b send-prefix

# Use shift + arrow key to move between windows in a session
bind -n S-Left  previous-window
bind -n S-Right next-window
# Prefix + / to search
bind-key / copy-mode \; send-key ?
# Prefix + a to enter copy mode
bind-key a copy-mode

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# bind K to ctrl+u in copy mode to scroll up half a page
bind -T copy-mode-vi K send -X halfpage-up
# bind J to ctrl+d in copy mode to scroll down half a page
bind -T copy-mode-vi J send -X halfpage-down

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin "wfxr/tmux-power"
set -g @tmux_power_theme 'everforest'
set -g @tmux_power_right_arrow_icon '' # ''
set -g @tmux_power_left_arrow_icon '' # ''
set -g @tmux_power_left_a  ' #S'          # session name
set -g @tmux_power_left_b  ''
set -g @tmux_power_left_c  ''
set -g @tmux_power_left_d  ''
set -g @tmux_power_right_w ''
set -g @tmux_power_right_x '#{b:pane_current_path}'
set -g @tmux_power_right_y ' %H:%M'         # time
set -g @tmux_power_right_z ' %F'         # date

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

